services:
  # Backend API Service
  - type: web
    name: youtube-narrative-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: web
    name: youtube-narrative-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm exec -- serve -s dist
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          name: youtube-narrative-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL
          suffix: /api
