services:
  # Backend API Service
  - type: web
    name: youtube-narrative-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    healthCheckPath: /api/health/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://youtube-narrative-frontend.onrender.com

  # Frontend Service
  - type: web
    name: youtube-narrative-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://youtube-narrative-api.onrender.com/api
